//
//  ProjectVersion.hpp
//  RealtekCardReader
//
//  Auto-generated by FireWolf on 2021/09/12.
//

#ifndef ProjectVersion_h
#define ProjectVersion_h

#define VERSION "0.9.7"
#define HASH "0b1a4c6"
#define TIME "Sun Sep 12 05:00:44 UTC 2021"

#endif /* ProjectVersion_h */
