//
//  ProjectVersion.hpp
//  RealtekCardReader
//
//  Auto-generated by FireWolf on 2021/09/12.
//

#ifndef ProjectVersion_h
#define ProjectVersion_h

#define VERSION "0.9.7"
#define HASH "ac9d59e"
#define TIME "Sun Sep 12 21:02:52 UTC 2021"

#endif /* ProjectVersion_h */
